[tool.pyright]
typeCheckingMode = "off"
useLibraryCodeForTypes =  true

[tool.black]
line-length = 88

[tool.flake8]
ignore = "E203, E266, E501, W503, F403, F401"
max-line-length = 88
max-complexity = 18
