# stage0_config.toml

# General settings
[general]
stage = "stage0"
tree_name = "rawTree"
nuclei = "127I"
numch = 32
fp_length = 21.5


[flags]
pu_flag = 32768
fo_flag = 65536


[binning]
hTOF_mus_down = 0
hTOF_mus_up = 1000
hTOF_mus_Nbins =100000

hTOF_ns_down = 0
hTOF_ns_up = 1000000
hTOF_ns_Nbins =100000

hPulseHeight_down = 0
hPulseHeight_up = 1000
hPulseHeight_Nbins =1000

[cuts]
hEn_cuts_on_hEgam = []
hEgam_cuts_on_hEn = []
