# stage0_config.toml

# General settings
[general]
stage = "stage0"
tree_name = "rawTree"
nuclei = "127I"
numch = 32

[constants]
fp_length = 21.5


[flags]
pu_flag = 32768
fo_flag = 65536


[binning]



[cuts]

