# Histograms
# Add new table to add more histograms 

############################################################################

# [histograms.hTOF_mus]
# name = "hTOF_mus"
# xaxis = "TOF [#mus]"
# yaxis = "counts"
# col = "tof_mus"
# gate = ""
# all = false
# bins.down = 0
# bins.up = 3000
# bins.N  = 300000 
# bins.var = false

# [histograms.hTOF_ns]
# name = "hTOF_ns"
# xaxis = "TOF [ns]"
# yaxis = "counts"
# col = "tof_ns"
# gate = ""
# all = false
# bins.down = 0
# bins.up = 300000
# bins.N  = 30000
# bins.var = false

# [histograms.hTOF_10ns]
# name = "hTOF_10ns"
# xaxis = "TOF [10ns]"
# yaxis = "counts"
# col = "tof"
# gate = ""
# all = false
# bins.down = 0
# bins.up = 300000 # default 100,000
# bins.N  = 300000 # degault 100,000
# bins.var = false


############################################################################

# [histograms.hPulseHeight]
# name = "hPulseHeight"
# xaxis = "pulse height"
# yaxis = "counts"
# col = "PulseHeight"
# gate = ""
# all = false
# bins.down = 0
# bins.up = 12000
# bins.N = 12000
# bins.var = false


############################################################################


[histograms.hEgam]
name = "hEgam"
xaxis = "Egam [keV]"
yaxis = "counts"
col = "Egam"
gate = "PulseHeight > 0"
all = false
bins.down = 0
bins.up = 12000
bins.N = 12000
bins.var = false

# [histograms.hEgam_all]
# name = "hEgam_all"
# xaxis = "Egam [keV]"
# yaxis = "counts"
# col = "Egam"
# gate = "PulseHeight > 0"
# all = true
# bins.down = 0
# bins.up = 12000
# bins.N = 12000
# bins.var = false


# [histograms.hEgam_coin0]
# name = "hEgam_coin0"
# xaxis = "Egam [keV]"
# yaxis = "counts"
# col = "Egam"
# gate = "Coin == 0 && PulseHeight > 0"
# all = false
# bins.down = 0
# bins.up = 12000
# bins.N = 12000
# bins.var = false

# [histograms.hEgam_coin1]
# name = "hEgam_coin1"
# xaxis = "Egam [keV]"
# yaxis = "counts"
# col = "Egam"
# gate = "Coin == 1 && PulseHeight > 0"
# all = false
# bins.down = 0
# bins.up = 12000
# bins.N = 12000
# bins.var = false


# [histograms.hEgam_gated_all]
# name = "hEgam_gated_all"
# xaxis = "Egam [keV]"
# yaxis = "counts"
# col = "Egam"
# gate = "En >= 0.68 && En <= 0.84 && PulseHeight > 0"
# all = true
# bins.down = 0
# bins.up = 12000
# bins.N = 12000
# bins.var = false

# [histograms.hEgam_gated_bkg_all]
# name = "hEgam_gated_bkg_all"
# xaxis = "Egam [keV]"
# yaxis = "counts"
# col = "Egam"
# gate = "((En >= 0.4 && En <= 0.6) || (En >= 0.9 && En <= 1.2)) && PulseHeight > 0"
# all = true
# bins.down = 0
# bins.up = 12000
# bins.N = 12000
# bins.var = false


############################################################################


[histograms.hEn]
name = "hEn"
xaxis = "En [eV]"
yaxis = "counts"
col = "En"
gate = ""
all = false
bins.down = 0
bins.up = 450000
bins.N = 450000
bins.var = true


# [histograms.hEn_all]
# name = "hEn_all"
# xaxis = "En [eV]"
# yaxis = "counts"
# col = "En"
# gate = ""
# all = true
# bins.down = 0
# bins.up = 450000
# bins.N = 450000
# bins.var = true

# [histograms.hEn_all_]
# name = "hEn_all_"
# xaxis = "En [eV]"
# yaxis = "counts"
# col = "En"
# gate = ""
# all = true
# bins.down = 0
# bins.up = 100
# bins.N = 100000
# bins.var = false

# [histograms.hEn_zero]  ######
# name = "hEn_zero"
# xaxis = "En [eV]"
# yaxis = "counts"
# col = "En"
# gate = "PulseHeight == 0"
# all = false
# bins.down = 0
# bins.up = 450000
# bins.N = 450000
# bins.var = true
# # bins.up = 100
# # bins.N = 100000
# # bins.var = false

# [histograms.hEn_gtzero] #####
# name = "hEn_gtzero"
# xaxis = "En [eV]"
# yaxis = "counts"
# col = "En"
# gate = "PulseHeight > 0"
# all = false
# bins.down = 0
# # bins.up = 450000
# # bins.N = 450000
# # bins.var = true
# bins.up = 100
# bins.N = 100000
# bins.var = false

# [histograms.hEn_pu]
# name = "hEn_pu"
# xaxis = "En [eV]"
# yaxis = "counts"
# col = "En"
# gate = "Flags == 32768"
# all = false
# bins.down = 0
# bins.up = 450000
# bins.N = 450000
# bins.var = true

# [histograms.hEn_npu]
# name = "hEn_npu"
# xaxis = "En [eV]"
# yaxis = "counts"
# col = "En"
# gate = "Flags != 32768"
# all = false
# bins.down = 0
# bins.up = 450000
# bins.N = 450000
# bins.var = true

# [histograms.hEn_npu_gtzero]
# name = "hEn_npu_gtzero"
# xaxis = "En [eV]"
# yaxis = "counts"
# col = "En"
# gate = "Flags != 32768 && PulseHeight > 0"
# all = false
# bins.down = 0
# bins.up = 450000
# bins.N = 450000
# bins.var = true



# [histograms.hEn_all_gate_Bo]
# name = "hEn_all_gate_Bo"
# xaxis = "En [eV]"
# yaxis = "counts"
# col = "En"
# gate = "Egam >= 466 && Egam <= 490"
# all = true
# bins.down = 0
# bins.up = 450000
# bins.N = 450000
# bins.var = true


[histograms.hEn_gate5098]
name = "hEn_gate5098"
xaxis = "En [eV]"
yaxis = "counts"
col = "En"
gate = "Egam >= 5058 && Egam <= 5107"
all = false
bins.down = 0
bins.up = 450000
bins.N = 450000
bins.var = true

# [histograms.hEn_gate5098_all]
# name = "hEn_gate5098_all"
# xaxis = "En [eV]"
# yaxis = "counts"
# col = "En"
# gate = "Egam >= 5058 && Egam <= 5107"
# all = true
# bins.down = 0
# bins.up = 450000
# bins.N = 450000
# bins.var = true

[histograms.hEn_gate5126]
name = "hEn_gate5126"
xaxis = "En [eV]"
yaxis = "counts"
col = "En"
gate = "Egam >= 5104 && Egam <= 5134"
all = false
bins.down = 0
bins.up = 450000
bins.N = 450000
bins.var = true

# [histograms.hEn_gate5126_all]
# name = "hEn_gate5126_all"
# xaxis = "En [eV]"
# yaxis = "counts"
# col = "En"
# gate = "Egam >= 5104 && Egam <= 5134"
# all = true
# bins.down = 0
# bins.up = 450000
# bins.N = 450000
# bins.var = true

# [histograms.hEn_gate5126_all_]
# name = "hEn_gate5126_all_"
# xaxis = "En [eV]"
# yaxis = "counts"
# col = "En"
# gate = "Egam >= 5104 && Egam <= 5134"
# all = true
# bins.down = 0
# bins.up = 100
# bins.N = 100000
# bins.var = false

[histograms.hEn_gate5161]
name = "hEn_gate5161"
xaxis = "En [eV]"
yaxis = "counts"
col = "En"
gate = "Egam >= 5134 && Egam <= 5164"
all = false
bins.down = 0
bins.up = 450000
bins.N = 450000
bins.var = true


# [histograms.hEn_gate5161_all]
# name = "hEn_gate5161_all"
# xaxis = "En [eV]"
# yaxis = "counts"
# col = "En"
# gate = "Egam >= 5134 && Egam <= 5164"
# all = true
# bins.down = 0
# bins.up = 450000
# bins.N = 450000
# bins.var = true


# [histograms.hEn_gatebkg]
# name = "hEn_gatebkg"
# xaxis = "En [eV]"
# yaxis = "counts"
# col = "En"
# gate = "(Egam >= 4980 && Egam <= 5050) || (Egam >= 5200 && Egam <= 5600)"
# all = false
# bins.down = 0
# # bins.up = 450000
# # bins.N = 450000
# # bins.var = true
# bins.up = 100
# bins.N = 100000
# bins.var = false

# [histograms.hEn_gatebkg_all]
# name = "hEn_gatebkg_all"
# xaxis = "En [eV]"
# yaxis = "counts"
# col = "En"
# gate = "(Egam >= 4980 && Egam <= 5050) || (Egam >= 5200 && Egam <= 5600)"
# all = true
# bins.down = 0
# bins.up = 450000
# bins.N = 450000
# bins.var = true


# [histograms.hEn_coin0]
# name = "hEn_coin0"
# xaxis = "En [eV]"
# yaxis = "counts"
# col = "En"
# gate = "Coin == 0"
# all = false
# bins.down = 0
# bins.up = 450000
# bins.N = 450000
# bins.var = true

# [histograms.hEn_coin1]
# name = "hEn_coin1"
# xaxis = "En [eV]"
# yaxis = "counts"
# col = "En"
# gate = "Coin == 1"
# all = false
# bins.down = 0
# bins.up = 450000
# bins.N = 450000
# bins.var = true


##################################################################################





