# Congfig for the stage 0 module. This config is loaded on module import.

[general]
stage = "stage0"
data_format = "2020" 
tree_name = "rawTree"
nuclei = "127I"
numch = 32
fp_length = 21.5
pu_flag = 32768
fo_flag = 65536

[paths]
hist_def = "../configs/hist_def.toml"
calib =  "../calib/calib_apr.csv"
run_info = "../data/run_info1.toml"
det_map = "../configs/dest_map.toml"
input = "../data/"
output = "../output/stage0_output.root"


