# stage0_config.toml

# general configuration
[general]
stage = "stage1"
tree_name = "rawTree"
nuclei = "127I"
numch = 32
fp_length = 21.5
pu_flag = 32768
fo_flag = 65536
INPUT_PATH = '../data/stage0_output.root'
OUTPUT_PATH = '../output/stage1_output.root'

