# Congfig for the stage 0 module. This config is loaded on module import.

[general]
stage = "stage0"
data_format = "new" 
tree_name = "rawTree"
nuclei = ""
numch = 32
fp_length = 21.5
pu_flag = 32768
fo_flag = 65536

# [paths]
# hist_def = "../configs/hist_def_2019apr_Cd.toml"
# calib =  "../calib/calib_2019apr.csv"
# run_info = "../data/run_info_2019apr.toml"
# input = "../data/"
# output = "../output/output.root"

# [paths]
# hist_def = "../configs/hist_def_2023apr_Cd.toml"
# calib =  "../calib/calib_2023apr.csv"
# run_info = "../data/run_info_2023apr_Cd.toml"
# input = "../data/"
# output = "../output/output.root"

# [paths]
# hist_def = "../configs/hist_def_2023dec_Cd.toml"
# # calib =  "../calib/calib_2023dec.csv"
# calib =  "../calib/calib_2023dec_Pr.csv"
# run_info = "../data/run_info_2023dec_Cd.toml"
# input = "../data/"
# output = "../output/output.root"


[paths]
hist_def = "../configs/hist_def_2024mar.toml"
# calib =  "../calib/calib_2023dec.csv"
calib =  "../calib/calib_2024mar.csv"
run_info = "../data/run_info_2024mar.toml"
input = "../data/"
output = "../output/2024mar/stage0_2024mar.root"