# stage0_config.toml

# general configuration
[general]
stage = "stage0"
tree_name = "rawTree"
nuclei = "127I"
numch = 32
fp_length = 21.5
pu_flag = 32768
fo_flag = 65536
CONFIG_PATH = "../configs/stage0_config.toml"
CALIB_PATH =  "../calib/calib_apr.csv"
INPUT_PATH = "../data/"
OUTPUT_PATH = "../output/stage0_output.root"


# Histograms
# Add new table to add more histograms 



[hist.hTOF_mus]
name = "hTOF_mus"
xaxis = "TOF [#mus]"
yaxis = "counts"
col = "tof_mus"
gate = ""
all = false
bins.down = 0
bins.up = 1000
bins.N = 100000
bins.var = false
pu_rate = true

# [hist.hTOF_ns]
# name = "hTOF_ns"
# xaxis = "TOF [ns]"
# yaxis = "counts"
# col = "tof_ns"
# gate = ""
# all = false
# bins.down = 0
# bins.up = 1000000
# bins.N = 100000
# bins.var = false

# [hist.hTOF_10ns]
# name = "hTOF_10ns"
# xaxis = "TOF [#mus]"
# yaxis = "counts"
# col = "tof"
# gate = ""
# all = false
# bins.down = 0
# bins.up = 100000
# bins.N = 100000
# bins.var = false

[hist.hEgam]
name = "hEgam"
xaxis = "Egam [keV]"
yaxis = "counts"
col = "Egam"
gate = ""
all = false
bins.down = 0
bins.up = 12000
bins.N = 12000
bins.var = false
pu_rate = true

[hist.hEn]
name = "hEn"
xaxis = "En [eV]"
yaxis = "counts"
col = "En"
gate = ""
all = false
bins.down = 0
bins.up = 100000
bins.N = 100000
bins.var = true
pu_rate = true

[hist.hEn_zero]
name = "hEn_zero"
xaxis = "En [eV]"
yaxis = "counts"
col = "En"
gate = "PulseHeight == 0"
all = false
bins.down = 0
bins.up = 100000
bins.N = 100000
bins.var = true
pu_rate = true

[hist.hEn_gt_zero]
name = "hEn_gt_zero"
xaxis = "En [eV]"
yaxis = "counts"
col = "En"
gate = "PulseHeight > 0"
all = false
bins.down = 0
bins.up = 100000
bins.N = 100000
bins.var = true
pu_rate = true

[hist.hEn_gate_FA]
name = "hEn_gate_FA"
xaxis = "En [eV]"
yaxis = "counts"
col = "En"
gate = "Egam >= 6637 && Egam <= 6702"
all = false
bins.down = 0
bins.up = 100000
bins.N = 100000
bins.var = true
pu_rate = true

[hist.hEn_gate_SE]
name = "hEn_gate_SE"
xaxis = "En [eV]"
yaxis = "counts"
col = "En"
gate = "Egam >= 6150 && Egam <= 6194"
all = false
bins.down = 0
bins.up = 100000
bins.N = 100000
bins.var = true
pu_rate = true

[hist.hEn_gate_FA_bkg]
name = "hEn_gate_FA_bkg"
xaxis = "En [eV]"
yaxis = "counts"
col = "En"
gate = "Egam >= 6777 && Egam <= 7044"
all = false
bins.down = 0
bins.up = 100000
bins.N = 100000
bins.var = true
pu_rate = true

[hist.hEn_all_gate_Bo]
name = "hEn_all_gate_Bo"
xaxis = "En [eV]"
yaxis = "counts"
col = "En"
gate = "Egam >= 466 && Egam <= 490"
all = true
bins.down = 0
bins.up = 100000
bins.N = 100000
bins.var = true
pu_rate = true



[binning]
hTOF_mus_down = 0
hTOF_mus_up = 1000
hTOF_mus_Nbins = 100000

hTOF_ns_down = 0
hTOF_ns_up = 1000000
hTOF_ns_Nbins = 100000

hTOF_10ns_down = 0
hTOF_10ns_up = 100000
hTOF_10ns_Nbins = 100000

hPulseHeight_down = 0
hPulseHeight_up = 10000
hPulseHeight_Nbins = 10000

[cuts]
hEn_cut_on_hEgam = [
    [
        "hEn_cut_FA",
        "Egam >= 6637 && Egam <= 6702",
    ],
    [
        "hEn_cut_SE",
        "Egam >= 6150 && Egam <= 6194",
    ],
    [
        "hEgam_cut_FA_bkg",
        "Egam >= 6777 && Egam <= 7044",
    ],
    [
        "hEn_all_gated_Bo",
        "Egam >= 466 && Egam <= 490",
    ],
]
hEgam_cut_on_hEn = []
