# stage0_config.toml

# general configuration
[general]
stage = "stage1"
tree_name = "rawTree"
nuclei = "127I"
numch = 32
fp_length = 21.5
pu_flag = 32768
fo_flag = 65536



[paths]
boron = "../output/stage0_output_beam_NaI.root"
cross_section = "../data/nndc_data.txt"
input = '../output/stage0_output_NaI1.root'
output = '../output/stage1_output_NaI1.root'
